name: '🏗️ Build Plugin'

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - AnitomySharp
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
      - AnitomySharp
    paths-ignore:
      - '**/*.md'


jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@master
